### ISSUE TITLE
Section 2 - Add styles for CTA box

### ISSUE THREAD

**Issue by josh76543210** [josh76543210/Collaboration---Frontend-Mentor---Huddle-landing-page-solution#10]
![cta](https://github.com/josh76543210/Collaboration---Frontend-Mentor---Huddle-landing-page-solution/assets/119835493/a3d718ff-ec77-44c5-a28a-c1a8cd64640c)

**Comment by ShalomiAhavah** [comment]
Creating PR right now(:
