### ISSUE TITLE
Section 2 - Position CTA box and add border

### ISSUE THREAD

**Issue by josh76543210** [josh76543210/Collaboration---Frontend-Mentor---Huddle-landing-page-solution#15]
Position the CTA box correctly and add a border.

![Screenshot 2024-03-29 at 21-23-25 Frontend Mentor Huddle landing page with alternating feature blocks](https://github.com/josh76543210/Collaboration---Frontend-Mentor---Huddle-landing-page-solution/assets/119835493/9e088073-004a-41ee-8ae2-fba3b03b8c45)

**Comment by ShalomiAhavah** [comment]
Got this one

**Comment by ShalomiAhavah** [comment]
Done I believe

**Comment by Leroy-sama** [comment]
I'll take care of it

**Comment by josh76543210** [comment]
Fixed by #21

**Comment by josh76543210** [comment]
Fixed by #21
